import Link from 'next/link'

function Screen({light=false}){return <div className={'case-screen '+(light?'light':'')}><div className="case-top"><i/><i/><i/></div><div className="case-ui"><aside/><section><div className="ui-heading"/><div className="ui-row"><i/><i/><i/></div><div className="ui-panel"><b/><b/><b/><b/><b/></div></section></div></div>}

export default function ReachStream(){
 return <main className="case-page">
  <header className="nav wrap"><Link href="/" className="brand">MALICK<span>.</span></Link><nav><a href="/#work">Work</a><a href="/#services">Services</a><a href="/#about">About</a><a href="/#contact">Contact</a></nav><a className="resume" href="mailto:hello@mhdesign4u.com">Let's work <span>↗</span></a></header>
  <div className="wrap case-nav"><Link href="/"><span>←</span> Back to work</Link><span>CASE STUDY · 01</span></div>
  <section className="wrap case-hero"><div className="eyebrow">REACHSTREAM · IN SNAP · 2018—2025</div><h1>Evolving a complex<br/><em>B2B data platform.</em></h1><p className="case-lede">A long-running product design journey across web, application and extension experiences — simplifying complex data workflows while the product itself continued to evolve.</p><div className="case-stats"><div><b>7+</b><span>YEARS OF<br/>EVOLUTION</span></div><div><b>WEB</b><span>PRODUCT<br/>EXPERIENCE</span></div><div><b>APP</b><span>APPLICATION<br/>EXPERIENCE</span></div><div><b>EXT</b><span>CHROME<br/>EXTENSION</span></div></div></section>
  <section className="case-hero-visual wrap"><Screen/></section>
  <section className="wrap case-content"><aside className="case-index"><span>01</span><span>02</span><span>03</span><span>04</span><span>05</span></aside><div>
   <section><span className="kicker">THE CONTEXT</span><h2>A product that kept growing.</h2><p>ReachStream evolved through multiple generations of the product. That meant new capabilities, new surfaces and new expectations — while the underlying challenge stayed the same: help users find, understand and act on business data without getting buried in complexity.</p><p>My role covered UX/UI design, product interface exploration, prototypes and web/application experiences across multiple iterations.</p></section>
   <section><span className="kicker">THE DESIGN CHALLENGE</span><h2>More capability shouldn't mean more cognitive load.</h2><div className="challenge-grid"><div><b>01</b><h3>Information density</h3><p>Large volumes of business data needed clear hierarchy and scanning patterns.</p></div><div><b>02</b><h3>Workflow complexity</h3><p>Users moved through search, filtering, selection and downstream actions.</p></div><div><b>03</b><h3>Product evolution</h3><p>New versions needed to feel coherent without being trapped by old patterns.</p></div></div></section>
   <section><span className="kicker">MY APPROACH</span><h2>Design the system, not just the screen.</h2><div className="approach-list"><div><b>01</b><span><strong>Map the experience</strong> Understand entry points, workflows, states and handoffs before polishing UI.</span></div><div><b>02</b><span><strong>Reduce visual noise</strong> Create hierarchy so users can scan dense information with confidence.</span></div><div><b>03</b><span><strong>Build reusable patterns</strong> Treat recurring interactions as a system rather than one-off screens.</span></div><div><b>04</b><span><strong>Prototype the behaviour</strong> Use interaction to test the experience before production.</span></div></div></section>
   <section><span className="kicker">EXPLORATION</span><h2>From structure to interface.</h2><div className="screen-stack"><Screen/><Screen light/></div></section>
   <section><span className="kicker">DESIGN SYSTEM THINKING</span><h2>Consistency is a product feature.</h2><p>Across a long-lived product, reusable components and interaction patterns become more than visual consistency. They reduce decision fatigue for users and make future product changes easier to design and build.</p><div className="tokens"><div><span>TYPE</span><strong>INTERFACE<br/>HIERARCHY</strong></div><div><span>GRID</span><strong>SPACING<br/>SYSTEM</strong></div><div><span>UI</span><strong>REUSABLE<br/>COMPONENTS</strong></div><div><span>STATE</span><strong>EMPTY · ERROR<br/>LOADING</strong></div></div></section>
   <section><span className="kicker">OUTCOME</span><h2>A more mature product language.</h2><p>The most meaningful outcome wasn't a single screen. It was the evolution of a consistent product experience across multiple generations, surfaces and workflows.</p><div className="outcome"><div><b>✓</b><span>Clearer information hierarchy</span></div><div><b>✓</b><span>Reusable interaction patterns</span></div><div><b>✓</b><span>Design continuity across iterations</span></div><div><b>✓</b><span>Closer collaboration with product & engineering</span></div></div><p className="disclaimer">This case study intentionally avoids invented business metrics. Quantitative product or usability results should only be added when supported by evidence.</p></section>
  </div></section>
  <section className="case-next"><div className="wrap"><span>NEXT CASE STUDY</span><h2>DataCaptive</h2><a href="/#work">Back to selected work <span>↗</span></a></div></section>
 </main>
}